/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package it.lule.cineteca.gui.jlist;

import it.lule.cineteca.logic.db.controller.DBMovieController;
import it.lule.cineteca.logic.db.entities.MovieEntity;
import it.lule.cineteca.logic.exceptions.dbException.abstractControllerException.DBAbstractControllerException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lele
 */
public class JlistJPanel extends javax.swing.JPanel {

    private MovieEntity movieEntity;

    /**
     * Creates new form JlistJPanel
     */
    public JlistJPanel() {
        initComponents();
        List<MovieEntity> allMovie = DBMovieController.getInstance().getAllMovie();

        for (MovieEntity movie : allMovie) {
            jlistModel1.addElement(movie);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlistModel1 = new it.lule.cineteca.gui.logic.rm.model.jlistModel();
        jlistRenderer1 = new it.lule.cineteca.gui.logic.rm.renderer.JlistRenderer();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();

        jlistRenderer1.setText("jlistRenderer1");

        jList1.setModel(jlistModel1);
        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Add");

        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRemove)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonRemove))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        try {
            Integer selectedIndex = jList1.getSelectedIndex();

            if (selectedIndex.equals(-1)) {
                return;
            }

            movieEntity = jlistModel1.get(selectedIndex);

            DBMovieController.getInstance().deleteMovie(movieEntity);
            jlistModel1.remove(selectedIndex);

            selectedIndex -= 1;

            if (selectedIndex.equals(-1)) {
                return;
            }
            jList1.setSelectedIndex(selectedIndex);
            
        } catch (DBAbstractControllerException ex) {
            Logger.getLogger(JlistJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JList<MovieEntity> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private it.lule.cineteca.gui.logic.rm.model.jlistModel jlistModel1;
    private it.lule.cineteca.gui.logic.rm.renderer.JlistRenderer jlistRenderer1;
    // End of variables declaration//GEN-END:variables
}
